export const SET_SPELLS = 'SET_SPELLS';
export const SET_SPELL = 'SET_SPELL';
export const SET_FAVORITES = 'SET_FAVORITES';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
